# Generated by Django 3.2.5 on 2021-07-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gaming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Gaming Article Title')),
                ('desc', models.CharField(max_length=200, verbose_name='Article Description')),
                ('author', models.CharField(default='Anon', max_length=60, verbose_name='Article Author')),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Greeting',
        ),
    ]
