# Generated by Django 3.2.5 on 2021-07-22 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0002_auto_20210721_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='User Email')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject Line')),
                ('message', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Essay Article Title')),
                ('desc', models.CharField(max_length=200, verbose_name='Article Description')),
                ('content', models.TextField(default='Placeholder', verbose_name='Article Content')),
                ('keywords', models.CharField(default='Placeholder', max_length=100, verbose_name='Article Keywords')),
                ('author', models.CharField(default='Anon', max_length=60, verbose_name='Article Author')),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='gaming',
            name='content',
            field=models.TextField(default='Placeholder', verbose_name='Article Content'),
        ),
        migrations.AddField(
            model_name='gaming',
            name='keywords',
            field=models.CharField(default='Placeholder', max_length=100, verbose_name='Article Keywords'),
        ),
    ]
