# Generated by Django 3.2.5 on 2021-07-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0003_auto_20210722_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='slug',
            field=models.CharField(default='djangodbmodelsfieldscharfield', max_length=100, verbose_name='Slug Title'),
        ),
        migrations.AddField(
            model_name='gaming',
            name='slug',
            field=models.CharField(default='djangodbmodelsfieldscharfield', max_length=100, verbose_name='Slug Title'),
        ),
    ]
