# Generated by Django 3.2.5 on 2021-07-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0004_auto_20210722_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaming',
            name='slug',
            field=models.SlugField(max_length=100, verbose_name='Slug Title'),
        ),
    ]
