# Generated by Django 3.2.5 on 2021-07-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0006_alter_gaming_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaming',
            name='thumb',
            field=models.CharField(default='test', max_length=100, verbose_name='Thumbnail Image'),
            preserve_default=False,
        ),
    ]
