# Generated by Django 3.2.5 on 2021-07-22 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0007_gaming_thumb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essay',
            name='slug',
            field=models.CharField(max_length=100, verbose_name='Slug Title'),
        ),
    ]
