# Generated by Django 3.2.5 on 2021-07-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0010_alter_essay_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='thumb',
            field=models.CharField(default='blog_site/img/Minecraft Video.png', max_length=100, verbose_name='Thumbnail Image'),
            preserve_default=False,
        ),
    ]
