# Generated by Django 3.2.5 on 2021-07-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0011_essay_thumb'),
    ]

    operations = [
        migrations.CreateModel(
            name='EIAChars',
            fields=[
                ('name', models.CharField(max_length=120, primary_key=True, serialize=False, verbose_name='Character Name')),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50, verbose_name='Keyword')),
            ],
        ),
        migrations.AddField(
            model_name='essay',
            name='type',
            field=models.CharField(default='Review', max_length=60, verbose_name='Article Type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gaming',
            name='type',
            field=models.CharField(default='Review', max_length=60, verbose_name='Article Type'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='essay',
            name='keywords',
        ),
        migrations.AddField(
            model_name='essay',
            name='keywords',
            field=models.ManyToManyField(to='blog_site.Keyword'),
        ),
    ]
