# Generated by Django 3.2.5 on 2021-07-30 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0012_auto_20210730_1652'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gaming',
            name='keywords',
        ),
        migrations.AddField(
            model_name='gaming',
            name='keywords',
            field=models.ManyToManyField(to='blog_site.Keyword'),
        ),
    ]
