# Generated by Django 3.2.5 on 2021-08-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0013_auto_20210730_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=60, verbose_name='Article Type')),
            ],
        ),
        migrations.DeleteModel(
            name='EIAChars',
        ),
        migrations.RemoveField(
            model_name='essay',
            name='type',
        ),
        migrations.RemoveField(
            model_name='gaming',
            name='type',
        ),
        migrations.AddField(
            model_name='essay',
            name='type',
            field=models.ManyToManyField(to='blog_site.Type'),
        ),
        migrations.AddField(
            model_name='gaming',
            name='type',
            field=models.ManyToManyField(to='blog_site.Type'),
        ),
    ]
