# Generated by Django 3.2.5 on 2021-08-08 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0015_auto_20210804_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Project Title')),
                ('thumb', models.CharField(max_length=100, verbose_name='Thumbnail Image')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, verbose_name='Slug Title')),
                ('desc', models.CharField(max_length=200, verbose_name='Project Description')),
                ('html', models.CharField(max_length=300, verbose_name='HTML to load')),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('last_edited', models.DateTimeField(auto_now=True)),
                ('article_type', models.CharField(default='project', max_length=50, verbose_name='Grouping Type')),
                ('keywords', models.ManyToManyField(to='blog_site.Keyword')),
                ('type', models.ManyToManyField(to='blog_site.Type')),
            ],
        ),
    ]
