# Generated by Django 3.2.5 on 2022-03-19 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_site', '0018_sudoku'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheatsheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50, verbose_name='Coding Language')),
                ('verbose', models.CharField(max_length=50, verbose_name='Coding Language for Display')),
            ],
            options={
                'verbose_name_plural': 'Cheatsheets',
            },
        ),
        migrations.AlterField(
            model_name='sudoku',
            name='board',
            field=models.CharField(max_length=500, verbose_name='Sudoku Board'),
        ),
        migrations.CreateModel(
            name='CheatsheetSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=50, verbose_name='Coding Language')),
                ('title', models.CharField(max_length=100, verbose_name='Section title')),
                ('code_block', models.CharField(max_length=500, verbose_name='Code Block Text')),
                ('description', models.CharField(max_length=1000, verbose_name='Section Description')),
                ('verbose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_site.cheatsheet')),
            ],
            options={
                'verbose_name_plural': 'Cheatsheet Sections',
            },
        ),
    ]
